apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-pv-nfs-data
spec:
  storageClassName: "nfs-nextcloud-data"
  capacity:
    storage: 100Gi
  accessModes:
    - "ReadWriteOnce"
  persistentVolumeReclaimPolicy: Retain 
  nfs:
    path: NEXTCLOUD_DATA_NFS_PATH         # < NFS share path on the server
    server: NFS_SERVER_IP                      # < IP address of your NFS server
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-pv-nfs-dbdata
spec:
  storageClassName: "nfs-nextcloud-dbdata"
  capacity:
    storage: 10Gi
  accessModes:
    - "ReadWriteOnce"
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: NEXTCLOUD_DBDATA_NFS_PATH      # < NFS share path on the server
    server: NFS_SERVER_IP                      # < IP address of your NFS server
    readOnly: false
